apiVersion: v1
kind: Secret

metadata:
  name: careertrack-php-secret
  namespace: careertrack

type: Opaque

stringData:
  APP_KEY: "base64:GENERATE_A_NEW_APP_KEY"
  DB_USERNAME: "careertrack"
  DB_PASSWORD: "CHANGE_ME!"