apiVersion: v1
kind: Service

metadata:
  name: careertrack-php
  namespace: careertrack

spec:
  selector:
    app: careertrack-php

  ports:
    - name: fastcgi
      protocol: TCP
      port: 9000
      targetPort: 9000

  type: ClusterIP