apiVersion: v1
kind: Secret

metadata:
  name: careertrack-mysql-secret
  namespace: careertrack

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME!"
  MYSQL_DATABASE: "careertrack"
  MYSQL_USER: "careertrack"
  MYSQL_PASSWORD: "CHANGE_ME!"