apiVersion: v1
kind: Service

metadata:
  name: careertrack-mysql
  namespace: careertrack

spec:
  clusterIP: None

  selector:
    app: careertrack-mysql

  ports:
    - name: mysql
      port: 3306
      targetPort: 3306